### ISSUE TITLE
Add Symfony3 to dependencies

### ISSUE THREAD

**Issue by madmis** [JBZoo/Data#1]
Hi, man. You make great work. 
But i want using this lib in my Symfony3 project and can't do this.

Can you fix `yml` depedency something like this `"~2.0|~3.0"`?

**Comment by SmetDenis** [comment]
Hi, thanks.

No problem. Can you create PR ?
I guess `^2.8|^3.0` is better. What do you think?

**Comment by madmis** [comment]
> I guess ^2.8|^3.0 is better. What do you think?
Yes. shure.

> Can you create PR ?
I willl try.

Thank you.

**Comment by SmetDenis** [comment]
Done by PR https://github.com/JBZoo/Data/pull/2
Use `1.x-dev` or `~1.4`

Thanks! =)
